from typing import Any

class GlomError(Exception): ...

def glom(target: Any, spec: Any, **kwargs: Any) -> Any: ...
def assign(target: Any, path: Any, val: Any, missing: Any = ...) -> Any: ...
def delete(target: Any, path: Any, ignore_missing: bool = ...) -> Any: ...
