from typing import Any

class StatusCode:
    ERROR: StatusCode
    OK: StatusCode
    UNSET: StatusCode

class Span:
    def set_attribute(self, key: str, value: Any) -> None: ...
    def set_status(self, status: StatusCode, description: str = ...) -> None: ...
    def end(self) -> None: ...
    def record_exception(self, exception: BaseException, **kwargs: Any) -> None: ...

class Tracer:
    def start_span(self, name: str, **kwargs: Any) -> Span: ...
    def start_as_current_span(self, name: str, **kwargs: Any) -> Any: ...

def get_tracer(name: str, **kwargs: Any) -> Tracer: ...
def set_tracer_provider(provider: Any) -> None: ...
def get_tracer_provider() -> Any: ...
