from __future__ import annotations

from collections.abc import Iterable
from typing import Iterator

from mitmproxy import connection, flow


class Headers:
    """Case-insensitive HTTP headers multi-mapping (str keys and values)."""

    def __init__(self, fields: Iterable[tuple[bytes, bytes]] = ..., **headers: str) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: str | None = ...) -> str | None: ...
    def items(self) -> Iterable[tuple[str, str]]: ...


class Message:
    @property
    def http_version(self) -> str: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def raw_content(self) -> bytes | None: ...
    @property
    def content(self) -> bytes | None: ...
    @content.setter
    def content(self, value: bytes | None) -> None: ...
    @property
    def text(self) -> str | None: ...
    @property
    def timestamp_start(self) -> float: ...
    @property
    def timestamp_end(self) -> float | None: ...


class Request(Message):
    @property
    def method(self) -> str: ...
    @method.setter
    def method(self, value: str) -> None: ...
    @property
    def scheme(self) -> str: ...
    @scheme.setter
    def scheme(self, value: str) -> None: ...
    @property
    def host(self) -> str: ...
    @host.setter
    def host(self, value: str) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, value: int) -> None: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, value: str) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def pretty_host(self) -> str: ...
    @property
    def pretty_url(self) -> str: ...
    @property
    def authority(self) -> str: ...


class Response(Message):
    @property
    def status_code(self) -> int: ...
    @property
    def reason(self) -> str: ...
    @classmethod
    def make(
        cls,
        status_code: int = ...,
        content: str | bytes = ...,
        headers: dict[str, str] = ...,
    ) -> Response: ...


class HTTPFlow(flow.Flow):
    request: Request
    response: Response | None
    error: flow.Error | None
    client_conn: connection.Client
    server_conn: connection.Server
