# Type stubs for langfuse
from typing import Any

class Langfuse:
    client: Any
    task_manager: Any
    def __init__(self, **kwargs: Any) -> None: ...
    def trace(self, **kwargs: Any) -> Any: ...
    def generation(self, **kwargs: Any) -> Any: ...
    def score(self, **kwargs: Any) -> Any: ...
    def flush(self) -> None: ...
    def shutdown(self) -> None: ...
