from typing import Any
from opentelemetry.sdk.resources import Resource

class TracerProvider:
    def __init__(self, resource: Resource | None = ...) -> None: ...
    def add_span_processor(self, processor: Any) -> None: ...
    def shutdown(self) -> None: ...
